name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.15.1
        with:
            webhook_url: ${{ secrets.WEBHOOK_URL }}
            color: "2105893"
            username: "Release Changelog"
            avatar_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
            content: "||@everyone||"
            footer_title: "Changelog"
            footer_icon_url: "https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png"
            footer_timestamp: true
            max_description: '4096'
            reduce_headings: true